package com.lbj.ecps.dao;

import com.lbj.ecps.model.EbItem;

public interface EbItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EB_ITEM
     *
     * @mbggenerated Mon Jan 15 22:53:49 CST 2018
     */
    int deleteByPrimaryKey(Long itemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EB_ITEM
     *
     * @mbggenerated Mon Jan 15 22:53:49 CST 2018
     */
    int insert(EbItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EB_ITEM
     *
     * @mbggenerated Mon Jan 15 22:53:49 CST 2018
     */
    int insertSelective(EbItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EB_ITEM
     *
     * @mbggenerated Mon Jan 15 22:53:49 CST 2018
     */
    EbItem selectByPrimaryKey(Long itemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EB_ITEM
     *
     * @mbggenerated Mon Jan 15 22:53:49 CST 2018
     */
    int updateByPrimaryKeySelective(EbItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EB_ITEM
     *
     * @mbggenerated Mon Jan 15 22:53:49 CST 2018
     */
    int updateByPrimaryKey(EbItem record);
}